dist: xenial
services:
  - docker

before_install:
- wget -O- http://neuro.debian.net/lists/xenial.us-nh.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
- sudo apt-key add .travis.singularity_key.txt
- sudo apt-get update
- sudo apt-get install -y singularity-container

language: python
cache:
  pip: true
  directories:
    - .mypy_cache

os:
  - linux
install:
  - pip install tox-travis
jobs:
  include:
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - python: "3.9-dev"
    - python: "3.8"
      name: "CWL v1.0 conformance tests"
      script: ${TRAVIS_BUILD_DIR}/travis.bash
      env:
       - version=v1.0
    - python: "3.8"
      name: "CWL v1.1 conformance tests"
      env:
       - version=v1.1
      script: ${TRAVIS_BUILD_DIR}/travis.bash
    - python: "3.7"
      script: RELEASE_SKIP=head ${TRAVIS_BUILD_DIR}/release-test.sh
      name: 'release test'
    - python: "3.8"
      name: "CWL v1.2 conformance tests"
      env:
       - version=v1.2.0-dev4
      script: ${TRAVIS_BUILD_DIR}/travis.bash
script: tox
branches:
  only:
    - main
    - just-bind-dirs
notifications:
  email: false
