[build-system]
requires = [
    "setuptools>=45",
    'mypy==0.971; python_version == "3.6"',  # last version for Python 3.6
    'mypy==1.3.0; python_version >= "3.7"',  # also update mypy-requirements.txt
    "types-requests",
    "types-psutil",
    "importlib_resources>=1.4",  # equivalent to Python 3.9
    "ruamel.yaml>=0.16.0,<0.18",
    "schema-salad>=8.2.20211104054942,<9",
    "cwl-utils >=0.19",
    'toml',
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 100
target-version = [ "py36" ]
