[build-system]
requires = [
    "setuptools>=45",
    "setuptools_scm[toml]>=8.0.4,<9",
    "mypy==1.10.1",  # also update mypy-requirements.txt
    "types-requests",
    "types-psutil",
    "importlib_resources>=1.4;python_version<'3.9'",
    "ruamel.yaml>=0.16.0,<0.18",
    "schema-salad>=8.4.20230426093816,<9",
    "cwl-utils>=0.32",
    "toml",
    "argcomplete>=1.12.0",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "cwltool/_version.py"

[tool.black]
line-length = 100
target-version = [ "py38" ]
